### ISSUE TITLE
Only the first checkbox in the sort/filter section of island_collections#show works

### ISSUE THREAD

**Issue by Secondbaker** [Secondbaker/AnimalCrossingTracker#3]
I don't know why it does this, but if there are two different checkboxes, it would appear that only the first works.  If there are multiple sets of the same checkboxes, the first checkbox works and the duplicate of the first checkbox toggles the original.

**Comment by abaker93** [comment]
https://codepen.io/GeoffreyCrofte/pen/BiHzp

**Comment by Secondbaker** [comment]
It turns out the labels needed the `for` attribute.
